name: kobin
description: "Kobin an ecommerce application"
publish_to: "none"
version: 1.3.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  svg_flutter: ^0.0.1
  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  pinput: ^5.0.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_switch: ^0.3.2
  flutter_dash: ^1.0.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_localization: ^0.3.1
  localization: ^2.1.1
  http: ^1.2.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.2.5
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.9.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/gif/

  fonts:
    - family: Poppins
      fonts:
        - asset: font/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: font/poppins/Poppins-SemiBold.ttf
          weight: 600
    - family: Optima LT
      fonts:
        - asset: font/Optima/Optima LT Bold.ttf
          weight: 600

flutter_intl:
  enabled: true



flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: false


flutter_native_splash:
  ...
